name: pull-from-emacswiki

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/emacsmirror
          key: ${{ runner.os }}-emacsmirror
      - run: |
          git clone --branch master --depth 1 "https://github.com/emacsmirror/emacswiki.org"  ~/emacsmirror \
          || (cd ~/emacsmirror && git fetch origin)

      - run: |
          cd ~/emacsmirror && git fetch origin --depth 1
