name: pull-from-emacswiki

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/emacsmirror
          key: ${{ runner.os }}-emacsmirror
      - run: |
          ls ~/
          git clone --branch master "https://github.com/emacsmirror/emacswiki.org" --depth 1 \
          || (ls emacsmirror && git fetch origin)

      - run: ls emacsmirror && git fetch origin --depth 1
